version: "3.3"

services:
  web:
    image: chemex
    build: .
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - .env:/var/www/chemex/.env

  db:
    image: mariadb:10
    volumes:
      - ./data/db:/var/lib/mysql
    env_file:
      - .env
