version: "3.4"

services:
  db:
    image: mariadb:10
    volumes:
      - ./data/db:/var/lib/mysql
    ports:
      - "3306:3306"
    env_file:
      - .env

  web:
    image: celaraze/chemex
    build: .
    depends_on:
      - db
    ports:
      - "80:80"
    volumes:
      - .env:/var/www/chemex/.env
