version: '1.0'
name: docker-build-prd
displayName: docker-build-prd
triggers:
  trigger: manual
  push:
    branches:
      precise:
        - main
stages:
  - name: stage-528ebcf8
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: cert
        certificate: 736d1ae0-7b9e-013a-0a92-3a7ff233c483
        tag: latest
        dockerfile: ./docker/Dockerfile
        isCache: false
permissions:
  - role: admin
    members: []
