version: '1.0'
name: docker-build-prd
displayName: docker-build-prd
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - main
stages:
  - name: stage-528ebcf8
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: cert
        certificate: a8f9bd10-7cbe-013a-9c35-2e64bcce1955
        tag: celaraze/chemex:latest
        dockerfile: ./docker-compose/gitee/Dockerfile
        isCache: false
permissions:
  - role: admin
    members: []
