version: '1.0'
name: docker-build-prd
displayName: docker-build-prd
triggers:
  trigger: manual
  push:
    branches:
      precise:
        - main
stages:
  - name: stage-528ebcf8
    displayName: 未命名
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@docker
        name: build_docker
        displayName: 镜像构建
        type: account
        repository: https://hub.docker.com/repository/docker/celaraze/chemex
        username: celaraze
        password: aiyanyan1314
        tag: chemex:latest
        dockerfile: ./docker/Dockerfile
        isCache: false
permissions:
  - role: admin
    members: []
